repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check .
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format .
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        pass_filenames: false
        always_run: true

      - id: pylint
        name: pylint
        entry: poetry run pylint .
        language: system
        pass_filenames: false
        always_run: true

      - id: commitizen
        name: commitizen check
        entry: poetry run cz check
        language: system
        stages: [commit-msg]
        args: [--commit-msg-file]
        pass_filenames: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: check-yaml
        exclude: ^docs/
      - id: check-added-large-files
        exclude: ^docs/
      - id: check-merge-conflict
        exclude: ^docs/
